server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/marllonDev/greeting-config-server
          #username: username(caso o repositório for privado)
          #password: password
          default-label: main
          search-paths:
          - 'greeting-service*'
